import type {Platform} from './NativeWallet';

const PATH_MAP: Record<Platform, Record<string, string>> = {
  ios: {
    en: require('../assets/buttons/ios/en.svg'),
    es: require('../assets/buttons/ios/es.svg'),
    fr: require('../assets/buttons/ios/fr.svg'),
    default: require('../assets/buttons/ios/en.svg'),
  },
  // Here you can find the expansion of language abbreviations used in the android part
  // https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes (Set 1)
  android: {
    af: require('../assets/buttons/android/af.png'),
    ar: require('../assets/buttons/android/ar.png'),
    az: require('../assets/buttons/android/az.png'),
    bg: require('../assets/buttons/android/bg.png'),
    bs: require('../assets/buttons/android/bs.png'),
    ca: require('../assets/buttons/android/ca.png'),
    cs: require('../assets/buttons/android/cs.png'),
    da: require('../assets/buttons/android/da.png'),
    de: require('../assets/buttons/android/da.png'),
    el: require('../assets/buttons/android/el.png'),
    en: require('../assets/buttons/android/en.png'),
    es: require('../assets/buttons/android/es.png'),
    et: require('../assets/buttons/android/et.png'),
    fi: require('../assets/buttons/android/fi.png'),
    fr: require('../assets/buttons/android/fr.png'),
    iw: require('../assets/buttons/android/he.png'),
    // Honk Kong Chinese
    hk: require('../assets/buttons/android/hk.png'),
    hr: require('../assets/buttons/android/hr.png'),
    hu: require('../assets/buttons/android/hu.png'),
    hy: require('../assets/buttons/android/hy.png'),
    id: require('../assets/buttons/android/id.png'),
    is: require('../assets/buttons/android/is.png'),
    it: require('../assets/buttons/android/it.png'),
    ja: require('../assets/buttons/android/ja.png'),
    ka: require('../assets/buttons/android/ka.png'),
    kk: require('../assets/buttons/android/kk.png'),
    km: require('../assets/buttons/android/km.png'),
    ko: require('../assets/buttons/android/ko.png'),
    ky: require('../assets/buttons/android/ky.png'),
    lt: require('../assets/buttons/android/lt.png'),
    lv: require('../assets/buttons/android/lv.png'),
    mk: require('../assets/buttons/android/mk.png'),
    ms: require('../assets/buttons/android/ms.png'),
    nl: require('../assets/buttons/android/nl.png'),
    no: require('../assets/buttons/android/no.png'),
    pl: require('../assets/buttons/android/pl.png'),
    pt: require('../assets/buttons/android/pt.png'),
    ro: require('../assets/buttons/android/ro.png'),
    ru: require('../assets/buttons/android/ru.png'),
    sk: require('../assets/buttons/android/sk.png'),
    sl: require('../assets/buttons/android/sl.png'),
    sq: require('../assets/buttons/android/sq.png'),
    sr: require('../assets/buttons/android/sr.png'),
    sv: require('../assets/buttons/android/sv.png'),
    sw: require('../assets/buttons/android/sw.png'),
    th: require('../assets/buttons/android/th.png'),
    tr: require('../assets/buttons/android/tr.png'),
    // Taiwanese Mandarin
    tw: require('../assets/buttons/android/tw.png'),
    uk: require('../assets/buttons/android/uk.png'),
    ur: require('../assets/buttons/android/ur.png'),
    uz: require('../assets/buttons/android/uz.png'),
    zh: require('../assets/buttons/android/zh.png'),
    zu: require('../assets/buttons/android/zu.png'),
    default: require('../assets/buttons/android/en.png'),
  },
};

export default PATH_MAP;
